### ISSUE TITLE
Getting half decoded pictures.

### ISSUE THREAD

**Issue by padram39** [songbihai/VideoDecoder#1]
I am using your h264 decoder to decode an inputstream, the thing is i am getting half decoded images , and by half decoded i mean the half of image is completly ok and other half is green / gray . any idea why this is happening?

**Comment by songbihai** [comment]
Please check if the i frame is received first

**Comment by padram39** [comment]
The problem was that the fps of the VideoPacket and the decoder plus the size of video packet and size of video of decoder were not the same.
setting the same packet size for decoder and VideoPacket and the same fps make it work , now im getting full images on simulator , but still getting -12909 on the real device.
