### ISSUE TITLE
Not able to decode h265 file format and see image

### ISSUE THREAD

**Issue by Arpit723** [songbihai/VideoDecoder#4]
Hi,

In my sample project, ios swift.

I am using VideoDecoder.

My input file sourcres are, 
https://drive.google.com/file/d/1Cb0wDOljfHwVHdOHFXAwD1MSueVOWSle/view?usp=sharing

I have tried to take the file,
And try to decode the file stream. 
But not able to get callback to see image.

Here is my sample code
https://github.com/Arpit723/VideoDecoderDemo.git

Would you please help me, to decode the file ?

**Comment by songbihai** [comment]
The demo contains h264 data, so H264Decoder should be used.
The data read here may not be very rigorous. It should be changed to: 
```while true {
            while ((startIndex + 3) < streamBuffer.count) {
                if [UInt8](streamBuffer[startIndex...startIndex+3]) == [0,0,0,1] {
                    let data = [UInt8](streamBuffer[0..<startIndex])
                    streamBuffer.removeSubrange(0..<startIndex)
                    return VideoPacket.init(data, fps: fps, type: type, videoSize: CGSize(width: 1920, height: 1080))
                }
                startIndex += 1
            }
            if startIndex > 4 {
                let data = [UInt8](streamBuffer[0...startIndex])
                streamBuffer.removeSubrange(0...startIndex)
                return VideoPacket.init(data, fps: fps, type: type, videoSize: CGSize(width: 1920, height: 1080))
            }
            return nil
            
        }

**Comment by Arpit723** [comment]
Thank you for quick reply. It works very well. And i could see images. Thanks
